# Generated by Django 3.1.3 on 2021-05-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_day', models.ManyToManyField(blank=True, to='main.Day')),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_superuser', models.IntegerField()),
                ('real_name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField()),
                ('date_joined', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='account.profile')),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
    ]
